// <auto-generated />
using System;
using InterStyle.Curtains.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterStyle.Curtains.Infrastructure.Migrations
{
    [DbContext(typeof(CurtainsDbContext))]
    [Migration("20260313052025_AddLocalization")]
    partial class AddLocalization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("curtains")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterStyle.Curtains.Domain.Curtain", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("picture_url");

                    b.Property<string>("PreviewUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("preview_url");

                    b.HasKey("Id");

                    b.ToTable("curtains", "curtains");
                });

            modelBuilder.Entity("InterStyle.Curtains.Domain.Curtain", b =>
                {
                    b.OwnsMany("InterStyle.Curtains.Domain.CurtainTranslation", "Translations", b1 =>
                        {
                            b1.Property<Guid>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<string>("Locale")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("locale");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.Property<Guid>("curtain_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("curtain_id", "Locale")
                                .IsUnique();

                            b1.ToTable("curtain_translations", "curtains");

                            b1.WithOwner()
                                .HasForeignKey("curtain_id");
                        });

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
