// <auto-generated />
using System;
using InterStyle.Leads.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterStyle.Leads.Infrastructure.Migrations
{
    [DbContext(typeof(LeadsDbContext))]
    [Migration("20260225081046_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("leads")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterStyle.Leads.Domain.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<int>("ServiceType")
                        .HasColumnType("integer")
                        .HasColumnName("service_type_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("leads", "leads");
                });

            modelBuilder.Entity("InterStyle.Leads.Domain.Lead", b =>
                {
                    b.OwnsOne("InterStyle.Leads.Domain.LeadRequestDetails", "RequestDetails", b1 =>
                        {
                            b1.Property<Guid>("LeadId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("address");

                            b1.Property<string>("Area")
                                .HasColumnType("text");

                            b1.Property<string>("Notes")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("notes");

                            b1.Property<bool>("RequiresInstallation")
                                .HasColumnType("boolean")
                                .HasColumnName("requires_installation");

                            b1.Property<int?>("WindowsCount")
                                .HasColumnType("integer");

                            b1.HasKey("LeadId");

                            b1.ToTable("leads", "leads");

                            b1.WithOwner()
                                .HasForeignKey("LeadId");
                        });

                    b.Navigation("RequestDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
